=== SachinDuplicate/-XML-musiclist/catalog_19033712.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="schema">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MusicStore">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="StoreINFO">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="StoreName"/>
                    <xs:element type="xs:string" name="logo"/>
                    <xs:element name="contact">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="Address"/>
                          <xs:element type="xs:string" name="Telephone"/>
                          <xs:element type="xs:anyURI" name="URL"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="MusicList">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Jazz">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Genre" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:string" name="Album"/>
                                <xs:element type="xs:string" name="img1" minOccurs="0"/>
                                <xs:element type="xs:string" name="img2" minOccurs="0"/>
                                <xs:element type="xs:string" name="img3" minOccurs="0"/>
								<xs:element name="Director">
									<xs:complexType mixed="true">
										<xs:sequence>
										  <xs:element type="xs:string" name="b" minOccurs="0"/>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
                                <xs:element name="Producer">
									<xs:complexType mixed="true">
										<xs:sequence>
										  <xs:element type="xs:string" name="b" minOccurs="0"/>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
                                <xs:element name="Writer">
                                  <xs:complexType mixed="true">
                                    <xs:sequence>
                                      <xs:element type="xs:string" name="b" minOccurs="0"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="MusicDescription">
                                  <xs:complexType mixed="true">
                                    <xs:sequence>
                                      <xs:element type="xs:string" name="b" minOccurs="0"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="Released">
                                  <xs:complexType mixed="true">
                                    <xs:sequence>
                                      <xs:element type="xs:string" name="b" minOccurs="0"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="Recorded">
                                  <xs:complexType mixed="true">
                                    <xs:sequence>
                                      <xs:element type="xs:string" name="b" minOccurs="0"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="description">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element type="xs:string" name="Title"/>
                                      <xs:element type="xs:string" name="AudioFormat"/>
                                      <xs:element type="xs:string" name="length"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute type="xs:string" name="Type" use="optional"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Rock">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Genre" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:string" name="Album"/>
								<xs:element type="xs:string" name="img4" minOccurs="0"/>
                                <xs:element type="xs:string" name="img5" minOccurs="0"/>
                                <xs:element type="xs:string" name="img6" minOccurs="0"/>
								<xs:element type="xs:string" name="Director"/>
                                <xs:element type="xs:string" name="Producer"/>
                                <xs:element type="xs:string" name="Writer"/>
                                <xs:element type="xs:string" name="MusicDescription"/>
                                <xs:element type="xs:string" name="Released"/>
                                <xs:element type="xs:string" name="Recorded"/>
                                <xs:element name="description">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element type="xs:string" name="Title"/>
                                      <xs:element type="xs:string" name="AudioFormat"/>
                                      <xs:element type="xs:string" name="length"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute type="xs:string" name="Type" use="optional"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="CountryMusic">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Genre" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:string" name="Album"/>
								<xs:element type="xs:string" name="img7" minOccurs="0"/>
                                <xs:element type="xs:string" name="img8" minOccurs="0"/>
                                <xs:element type="xs:string" name="img9" minOccurs="0"/>
								<xs:element type="xs:string" name="Director"/>
                                <xs:element type="xs:string" name="Producer"/>
                                <xs:element type="xs:string" name="Writer"/>
                                <xs:element type="xs:string" name="MusicDescription"/>
                                <xs:element type="xs:string" name="Released"/>
                                <xs:element type="xs:string" name="Recorded"/>
                                <xs:element name="description">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element type="xs:string" name="Title"/>
                                      <xs:element type="xs:string" name="AudioFormat"/>
                                      <xs:element type="xs:string" name="length"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute type="xs:string" name="Type" use="optional"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="PopMusic">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Genre" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:string" name="Album"/>
								<xs:element type="xs:string" name="img10" minOccurs="0"/>
                                <xs:element type="xs:string" name="img11" minOccurs="0"/>
                                <xs:element type="xs:string" name="img12" minOccurs="0"/>
								<xs:element type="xs:string" name="Director"/>
                                <xs:element type="xs:string" name="Producer"/>
                                <xs:element type="xs:string" name="Writer"/>
                                <xs:element type="xs:string" name="MusicDescription"/>
                                <xs:element type="xs:string" name="Released"/>
                                <xs:element type="xs:string" name="Recorded"/>
                                <xs:element name="description">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element type="xs:string" name="Title"/>
                                      <xs:element type="xs:string" name="AudioFormat"/>
                                      <xs:element type="xs:string" name="length"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute type="xs:string" name="Type" use="optional"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
					<xs:element name="Dubstep">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Genre" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:string" name="Album"/>
								<xs:element type="xs:string" name="img13" minOccurs="0"/>
                                <xs:element type="xs:string" name="img14" minOccurs="0"/>
                                <xs:element type="xs:string" name="img15" minOccurs="0"/>
								<xs:element type="xs:string" name="Director"/>
                                <xs:element type="xs:string" name="Producer"/>
                                <xs:element type="xs:string" name="Writer"/>
                                <xs:element type="xs:string" name="MusicDescription"/>
                                <xs:element type="xs:string" name="Released"/>
                                <xs:element type="xs:string" name="Recorded"/>
                                <xs:element name="description">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element type="xs:string" name="Title"/>
                                      <xs:element type="xs:string" name="AudioFormat"/>
                                      <xs:element type="xs:string" name="length"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute type="xs:string" name="Type" use="optional"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== SachinDuplicate/-XML-musiclist/Catalog_19033712.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet type="text/css" href="Catalog_19033712.css"?>

<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Catalog_19033712.xsd">

<MusicStore>
	<StoreINFO>
		<StoreName>Duplicate Music Store</StoreName>
		<logo></logo>
		<contact>
			<Address>Kathmandu, Nepal</Address>
			<Telephone>Phone: 01234567</Telephone>
			<URL>www.duplicatemusic.com</URL>
		</contact>
	</StoreINFO>
	
	<MusicList>
		<Jazz>
			<Genre Type="Jazz">
				<Album>Time Out</Album>
				<img1></img1>
				<Director>Director: </Director>
				<Producer>Producer: Teo Macero</Producer>
				<Writer>Writer: Paul Desmond</Writer>
				<MusicDescription>Description: "Take Five" is a jazz standard composed by saxophonist Paul Desmond and originally recorded by the Dave Brubeck Quartet for their album[a][2] Time Out.The single was inducted into the Grammy Hall of Fame in 1996.</MusicDescription>
				<Released>Released: September 21, 1959</Released>
				<Recorded>Recorded: July 1, 1959</Recorded>
				<description>
					<Title>Title: Take Five</Title>
					<AudioFormat>Audio Format: Vinyl records</AudioFormat>
					<length>Length: 2:55(single version)</length>
				</description>
			</Genre>
				
			<Genre Type="Jazz">
				<Album>Kind of Blue</Album>
				<img2></img2>
				<Director>Director: </Director>
				<Producer>Producer: Teo Macero</Producer>
				<Writer>Writer: Miles Davis</Writer>
				<MusicDescription>Description: "So What" is one of the best known examples of modal jazz, set in the Dorian mode and consisting of 16 bars of D Dorian, followed by eight bars of E♭ Dorian and another eight of D Dorian.[1] This AABA structure puts it in the thirty-two-bar format of American popular song.</MusicDescription>
				<Released>Released: August 17, 1959</Released>
				<Recorded>Recorded: March 2, 1959</Recorded>
				<description>
					<Title>Title: So What</Title>
					<AudioFormat>AudioFormat: Compact disc</AudioFormat>
					<length>Length: 9:22</length>
				</description>
			</Genre>
			
			<Genre Type="Jazz">
				<Album>Data Lords</Album>
				<img3></img3>
				<Director>Director: </Director>
				<Producer>Producer: Maria Schneider, Brian Camelio, Ryan Truesdell</Producer>
				<Writer>Writer: Maria Schneider Orchestra</Writer>
				<MusicDescription>Description: Data Lords is an album by the Maria Schneider Orchestra that was released in 2020. It liner notes call "a story of two worlds" and are much like a two-disk release. The two sections are named "The Digital World" and the "The Natural World".The album won the Grammy Award for Best Large Jazz Ensemble Album in 2021, and the track "Sputnik" won the Grammy Award for Best Instrumental Composition.</MusicDescription>
				<Released>Released: July 24, 2020</Released>
				<Recorded>Recorded: August 30, 2019 - September 2, 2019</Recorded>
				<description>
					<Title>Title: Sputnik</Title>
					<AudioFormat>AudioFormat: vinyl records</AudioFormat>
					<length>Length: 8:10</length>
				</description>
			</Genre>			
		</Jazz>
		<Rock>
			<Genre Type="Rock">
				<Album>A Night at the Opera</Album>
				<img4></img4>
				<Director>Director: Bruce Gowers</Director>
				<Producer>Producer: Roy Thomas Baker</Producer>
				<Writer>Writer: Freddie Mercury</Writer>
				<MusicDescription>Description: "Bohemian Rhapsody" is a song by the British rock band Queen. The song is a six-minute suite,[1] notable for its lack of a refraining chorus and consisting of several sections: an intro, a ballad segment, an operatic passage, a hard rock part and a reflective coda. It  achieve widespread commercial success and appeal to a mainstream audience.</MusicDescription>
				<Released>Released: 31 October 1975</Released>
				<Recorded>Recorded:August–September 1975</Recorded>
				<description>
					<Title>Title: Bohemian Rhapsody</Title>
					<AudioFormat>Audio Format: Vinyl records, MP3</AudioFormat>
					<length>Length: 5:55</length>
				</description>
			</Genre>
			
			<Genre Type="Rock">
				<Album> Hotel California </Album>
				<img5></img5>
				<Director>Director: </Director>
				<Producer>Producer: Bill Szymczyk</Producer>
				<Writer>Writer: Don Felder, Don Henley, Glenn Frey</Writer>
				<MusicDescription>Description: "Hotel California" is the title track from the Eagles' album of the same name. The song is considered the most famous recording by the band, and in 1998 its long guitar coda was voted the best guitar solo of all time by readers of Guitarist.</MusicDescription>
				<Released>Released: February 22, 1977</Released>
				<Recorded>Recorded: 1976</Recorded>
				<description>
					<Title>Title: Hotel California</Title>
					<AudioFormat>Audio Format:Compact disc, MP3 </AudioFormat>
					<length> Length: 6:30</length>
				</description>
			</Genre>

			<Genre Type="Rock">
				<Album>The Wall</Album>
				<img6></img6>
				<Director>Director: </Director>
				<Producer>Producer: Bob Ezrin, David Gilmour, James Guthrie, Roger Waters</Producer>
				<Writer>Writer: David Gilmour, Roger Waters</Writer>
				<MusicDescription>Description: "Comfortably Numb" is a song on Pink Floyd's eleventh album, The Wall (1979). It was released as a single in 1980 with "Hey You" as the B-side. "Comfortably Numb" is one of Pink Floyd's most well-known songs, notable for its two guitar solos. An early version was included on the 2012 Wall "Immersion Box Set".</MusicDescription>
				<Released>Released: 23 June 1980</Released>
				<Recorded>Recorded: April–November 1979</Recorded>
				<description>
					<Title>Title: Confortably Numb</Title>
					<AudioFormat>AudioFormat: </AudioFormat>
					<length>Length: 3:59(single edit)</length>
				</description>
			</Genre>
		</Rock>
		<CountryMusic>
			<Genre Type="CountryMusic">
				<Album>Goldmine</Album>
				<img7></img7>
				<Director>Director: Taylor Kelly, Brian Vaughan</Director>
				<Producer>Producer: Zach Kale, Ross Copperman</Producer>
				<Writer>Writer: Gabby Barrett, Zach Kale, Jon Nite</Writer>
				<MusicDescription>Description: "I Hope" is a song co-written and recorded by American country music singer Gabby Barrett. The song received a Country Music Association Award for Single of the Year nomination at the 54th Annual CMA Awards.</MusicDescription>
				<Released>Released: July 29, 2019</Released>
				<Recorded>Recorded: 2019</Recorded>
				<description>
					<Title>Title: I hope</Title>
					<AudioFormat>Audio Format: MP3</AudioFormat>
					<length>Length: 3:23</length>
				</description>
			</Genre>
			
			<Genre Type="CountryMusic">
				<Album>Johnny Cash with His Hot and Blue Guitar!</Album>
				<img8></img8>
				<Director>Director: </Director>
				<Producer>Producer: Sam Phillips</Producer>
				<Writer>Writer: Johnny Cash</Writer>
				<MusicDescription>Description: I Walk the Line" is a song written and recorded in 1956 by Johnny Cash. After three attempts with moderate chart ratings, it became Cash's first #1 hit on the Billboard charts, eventually reaching #17 on the US pop charts.</MusicDescription>
				<Released>Released: May 1, 1956</Released>
				<Recorded>Recorded: April 2, 1956</Recorded>
				<description>
					<Title>Title: I Walk The Line</Title>
					<AudioFormat>Audio Format: Vinyl records</AudioFormat>
					<length>Length: 2:45</length>
				</description>
			</Genre>
			
			<Genre Type="CountryMusic">
				<Album>Tangled Up</Album>
				<img9></img9>
				<Director>Director: TK McKamy</Director>
				<Producer>Producer: Dann Huff, Jesse Frasure</Producer>
				<Writer>Writer: Thomas Rhett, Sean Douglas, Joe Spargur</Writer>
				<MusicDescription>Description: "Die a Happy Man" is a song co-written and recorded by American country music singer Thomas Rhett. The song peaked at number 21 on the US Billboard Hot 100, becoming his highest-charting single on that chart.</MusicDescription>
				<Released>Released: September 28, 2015</Released>
				<Recorded>Recorded: 2015</Recorded>
				<description>
					<Title>Title: Die a Happy Man</Title>
					<AudioFormat>AudioFormat: MP3</AudioFormat>
					<length>Length: 3:47</length>
				</description>
			</Genre>
		</CountryMusic>
		<PopMusic>
			<Genre Type="PopMusic">
				<Album>Teenage Dream</Album>
				<img10></img10>
				<Director>Director: Dave Meyers</Director>
				<Producer>Producer: StargateSandy Vee</Producer>
				<Writer>Writer: Katy Perry, Mikkel S. Eriksen, Tor Erik Hermansen, Sandy Wilhelm, Ester Dean</Writer>
				<MusicDescription>Description: "Firework" is a song co-written and recorded by American singer Katy Perry from her third studio album. The song was commercially successful, reaching number 1 on the Billboard Hot 100 and the top five on 20 charts around the world. "Firework" has sold over 1 million copies in the United Kingdom.</MusicDescription>
				<Released>Released: October 26, 2010</Released>
				<Recorded>Recorded: 2010</Recorded>
				<description>
					<Title>Title: Firework</Title>
					<AudioFormat>Audio Format: MP3, WAV</AudioFormat>
					<length>Length: 3:48</length>
				</description>
			</Genre>

			<Genre Type="PopMusic">
				<Album>Purpose</Album>
				<img11></img11>
				<Director>Director: Parris Goebel</Director>
				<Producer>Producer: Skrillex, BloodPop</Producer>
				<Writer>Writer: Justin Bieber</Writer>
				<MusicDescription>Description: "Sorry" is a song recorded by Canadian singer Justin Bieber for his fourth studio album, Purpose. Commercially, the song topped the charts of thirteen countries. It spent seven weeks at number one on the Canadian Hot 100 and three weeks at number one on the US Billboard Hot 100.</MusicDescription>
				<Released>Released: October 22, 2015</Released>
				<Recorded>Recorded: 2015</Recorded>
				<description>
					<Title>Title: Sorry</Title>
